# Generated by Django 3.0.5 on 2020-05-17 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_study_guide_published'),
    ]

    operations = [
        migrations.DeleteModel(
            name='study_guide',
        ),
    ]
